const stundentPicks = [
  { "isbn": "9784309413181", "size": 2 },
  { "isbn": "9784065184479", "size": 2 },
  { "isbn": "9784041060575", "size": 2 },
  { "isbn": "9784120057090", "size": 2 },
  { "isbn": "9784101092058", "size": 2 },
  { "isbn": "9784098607785", "size": 8 },
  { "isbn": "9784488420147", "size": 2 },
  { "isbn": "9784041092453", "size": 2 },
  { "isbn": "9784103522348", "size": 2 },
  { "isbn": "9784163915098", "size": 2 },
  { "isbn": "9784575590043", "size": 2 },
  { "isbn": "9784813716112", "size": 2 },
  { "isbn": "9784091237545", "size": 8 },
  { "isbn": "9784048926669", "size": 2 },
  { "isbn": "9784043878017", "size": 2 },
  { "isbn": "9784101098104", "size": 2 },
  { "isbn": "9784150119553", "size": 2 },
  { "isbn": "9784062769211", "size": 2 },
  { "isbn": "9784062153065", "size": 2 },
  { "isbn": "9784101001579", "size": 2 },
  { "isbn": "9784102018040", "size": 2 },
  { "isbn": "9784101005010", "size": 2 },
  { "isbn": "9784097263722", "size": 7 },
  { "isbn": "9784591097663", "size": 7 },
  { "isbn": "9784265062591", "size": 7 },
  { "isbn": "9784774611600", "size": 8 },
  { "isbn": "9784772100311", "size": 2 },
  { "isbn": "9784838729470", "size": 2 },
  { "isbn": "9784041055069", "size": 2 },
  { "isbn": "9784102122044", "size": 2 },
  { "isbn": "9784101269313", "size": 2 },
  { "isbn": "9784041067505", "size": 2 },
  { "isbn": "9784864726115", "size": 3 },
  { "isbn": "9784591160022", "size": 2 },
  { "isbn": "9784864106269", "size": 2 },
  { "isbn": "9784575522099", "size": 2 },
  { "isbn": "9784061473928", "size": 2 },
  { "isbn": "9784062120630", "size": 2 },
  { "isbn": "9784044292010", "size": 2 },
  { "isbn": "9784061484467", "size": 2 },
  { "isbn": "9784061485136", "size": 2 },
  { "isbn": "9784591113073", "size": 2 },
  { "isbn": "9784494004676", "size": 2 },
  { "isbn": "9784046313430", "size": 2 },
  { "isbn": "9784566024113", "size": 7 },
  { "isbn": "9784001145014", "size": 2 },
  { "isbn": "9784797329834", "size": 2 },
  { "isbn": "9784065122105", "size": 2 },
  { "isbn": "9784048737432", "size": 2 },
  { "isbn": "9784094071993", "size": 2 },
  { "isbn": "9784620108193", "size": 7 },
  { "isbn": "9784103549512", "size": 2 },
  { "isbn": "9784591153093", "size": 2 },
  { "isbn": "9784041160084", "size": 2 },
  { "isbn": "9784041026229", "size": 2 },
  { "isbn": "9784333019120", "size": 7 },
  { "isbn": "9784434108716", "size": 2 },
  { "isbn": "9784799322703", "size": 2 },
  { "isbn": "9781368022286", "size": 2 },
  { "isbn": "9784562056286", "size": 2 },
  { "isbn": "9784152092854", "size": 2 }
]

const designBooks = [
  {
    "isbn": "9784140912027",
    "jpno": null,
    "link": null,
    "title": "琳派のデザイン学",
    "titleKana": "リンパ ノ デザインガク",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "NHKブックス",
    "seriesTitleKana": "エヌエイチケイ ブックス",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "三井 秀樹",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "NHK出版",
    "publisherKana": null,
    "issued": null,
    "date": "2013-02-01",
    "price": 1200,
    "extent": "250p",
    "pages": 250,
    "height": null,
    "subjects": "光琳派 ; KC141 ; 721.5",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784140885246",
    "jpno": null,
    "link": null,
    "title": "「あなた」という商品を高く売る方法",
    "titleKana": "アナタ ト イウ ショウヒン オ タカク ウル ホウホウ",
    "subtitle": "キャリア戦略をマーケティングから考える",
    "subtitleKana": "キャリア センリャク オ マーケティング カラ カンガエル",
    "seriesTitle": "NHK出版新書",
    "seriesTitleKana": "エヌエイチケー シュッパン シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "永井 孝尚",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "NHK出版",
    "publisherKana": null,
    "issued": null,
    "date": "2017-08-01",
    "price": 780,
    "extent": "203p",
    "pages": 203,
    "height": null,
    "subjects": "キャリアデザイン ; EL121 ; 366.29",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784569837390",
    "jpno": null,
    "link": null,
    "title": "大量生産品のデザイン論",
    "titleKana": "タイリョウ セイサンヒン ノ デザインロン",
    "subtitle": "経済と文化を分けない思考",
    "subtitleKana": "ケイザイ ト ブンカ オ ワケナイ シコウ",
    "seriesTitle": "PHP新書",
    "seriesTitleKana": "ピーエイチピー シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "佐藤 卓",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "PHP研究所",
    "publisherKana": null,
    "issued": null,
    "date": "2018-01-01",
    "price": 860,
    "extent": "245p",
    "pages": 245,
    "height": null,
    "subjects": "パッケージデザイン ; DH432 ; 675.18",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784569709017",
    "jpno": null,
    "link": null,
    "title": "自分らしいキャリアのつくり方",
    "titleKana": "ジブンラシイ キャリア ノ ツクリカタ",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "PHP新書",
    "seriesTitleKana": "PHP シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "高橋 俊介",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "PHP研究所",
    "publisherKana": null,
    "issued": null,
    "date": "2009-09-01",
    "price": 700,
    "extent": "197p",
    "pages": 197,
    "height": null,
    "subjects": "キャリアデザイン ; DH311 ; 336.4",
    "subjectKana": "[]"
  },
  {
    "isbn": "456961941X",
    "jpno": null,
    "link": null,
    "title": "働くひとのためのキャリア・デザイン",
    "titleKana": "ハタラク ヒト ノ タメノ キャリア デザイン",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "PHP新書",
    "seriesTitleKana": "PHP シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "金井 寿宏",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "PHP研究所",
    "publisherKana": null,
    "issued": null,
    "date": "2002-01-01",
    "price": 780,
    "extent": "299, 6p",
    "pages": 305,
    "height": null,
    "subjects": "キャリアデザイン ; EL121 ; 366.29",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784797367072",
    "jpno": null,
    "link": null,
    "title": "デザインセンスを身につける",
    "titleKana": "デザイン センス オ ミニツケル",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "ソフトバンク新書",
    "seriesTitleKana": "ソフトバンク シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "ウジ トモコ",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "ソフトバンククリエイティブ",
    "publisherKana": null,
    "issued": null,
    "date": "2011-09-01",
    "price": 760,
    "extent": "223p",
    "pages": 223,
    "height": null,
    "subjects": "デザイン ; KC521 ; 757",
    "subjectKana": "[]"
  },
  {
    "isbn": "479733794X",
    "jpno": null,
    "link": null,
    "title": "デザインにひそむ〈美しさ〉の法則",
    "titleKana": "デザイン ニ ヒソム ウツクシサ ノ ホウソク",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "ソフトバンク新書",
    "seriesTitleKana": "ソフトバンク シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "木全 賢",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "ソフトバンククリエイティブ",
    "publisherKana": null,
    "issued": null,
    "date": "2006-12-01",
    "price": 700,
    "extent": "169p",
    "pages": 169,
    "height": null,
    "subjects": "工業デザイン ; M371 ; 501.83",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784797356977",
    "jpno": null,
    "link": null,
    "title": "売れるデザインの発想法",
    "titleKana": "ウレル デザイン ノ ハッソウホウ",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "ソフトバンク新書",
    "seriesTitleKana": "ソフトバンク シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "木全 賢",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "ソフトバンククリエイティブ",
    "publisherKana": null,
    "issued": null,
    "date": "2009-12-01",
    "price": 730,
    "extent": "205p",
    "pages": 205,
    "height": null,
    "subjects": "工業デザイン ; M371 ; 501.8",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784797348897",
    "jpno": null,
    "link": null,
    "title": "人生迷子のシングルたち",
    "titleKana": "ジンセイ マイゴ ノ シングルタチ",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "ソフトバンク新書",
    "seriesTitleKana": "ソフトバンク シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "小島 貴子",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "ソフトバンククリエイティブ",
    "publisherKana": null,
    "issued": null,
    "date": "2008-10-01",
    "price": 730,
    "extent": "214p",
    "pages": 214,
    "height": null,
    "subjects": "キャリアデザイン ; EL121 ; 366.29",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784480683632",
    "jpno": null,
    "link": null,
    "title": "世界はデザインでできている",
    "titleKana": "セカイ ワ デザイン デ デキテ イル",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "ちくまプリマー新書",
    "seriesTitleKana": "チクマ プリマー シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "秋山 具義",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "筑摩書房",
    "publisherKana": null,
    "issued": null,
    "date": "2019-11-01",
    "price": 760,
    "extent": "147p",
    "pages": 147,
    "height": null,
    "subjects": "グラフィック・アート ; Y6 ; 727",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784480439628",
    "jpno": null,
    "link": null,
    "title": "デザインの仕事",
    "titleKana": "デザイン ノ シゴト",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "ちくま文庫",
    "seriesTitleKana": "チクマ ブンコ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "寄藤 文平・木村 俊介",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "筑摩書房",
    "publisherKana": null,
    "issued": null,
    "date": "2024-06-01",
    "price": 840,
    "extent": "230p",
    "pages": 230,
    "height": null,
    "subjects": "デザイン ; KC521 ; 757",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784480438003",
    "jpno": null,
    "link": null,
    "title": "線の冒険",
    "titleKana": "セン ノ ボウケン",
    "subtitle": "デザインの事件簿",
    "subtitleKana": "デザイン ノ ジケンボ",
    "seriesTitle": "ちくま文庫",
    "seriesTitleKana": "チクマ ブンコ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "松田 行正",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "筑摩書房",
    "publisherKana": null,
    "issued": null,
    "date": "2022-02-01",
    "price": 1500,
    "extent": "390p",
    "pages": 390,
    "height": null,
    "subjects": "デザイン ; KC521 ; 757",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784480436634",
    "jpno": null,
    "link": null,
    "title": "ひとの居場所をつくる",
    "titleKana": "ヒト ノ イバショ オ ツクル",
    "subtitle": "ランドスケープ・デザイナー田瀬理夫さんの話をつうじて",
    "subtitleKana": "ランドスケープ デザイナー タセ ミチオ サン ノ ハナシ オ ツウジテ",
    "seriesTitle": "ちくま文庫",
    "seriesTitleKana": "チクマ ブンコ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "西村 佳哲",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "筑摩書房",
    "publisherKana": null,
    "issued": null,
    "date": "2020-05-01",
    "price": 860,
    "extent": "274p",
    "pages": 274,
    "height": null,
    "subjects": "景観デザイン ; KA421 ; 518.8",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784480072290",
    "jpno": null,
    "link": null,
    "title": "対話をデザインする",
    "titleKana": "タイワ オ デザイン スル",
    "subtitle": "伝わるとはどういうことか",
    "subtitleKana": "ツタワル トワ ドウイウ コト カ",
    "seriesTitle": "ちくま新書",
    "seriesTitleKana": "チクマ シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "細川 英雄",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "筑摩書房",
    "publisherKana": null,
    "issued": null,
    "date": "2019-06-01",
    "price": 840,
    "extent": "236p",
    "pages": 236,
    "height": null,
    "subjects": "パーソナルコミュニケーション ; EC235 ; 361.454",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784480071163",
    "jpno": null,
    "link": null,
    "title": "オリンピックと万博",
    "titleKana": "オリンピック ト バンパク",
    "subtitle": "巨大イベントのデザイン史",
    "subtitleKana": "キョダイ イベント ノ デザインシ",
    "seriesTitle": "ちくま新書",
    "seriesTitleKana": "チクマ シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "暮沢 剛巳",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "筑摩書房",
    "publisherKana": null,
    "issued": null,
    "date": "2018-02-01",
    "price": 860,
    "extent": "270p",
    "pages": 270,
    "height": null,
    "subjects": "デザイン ; 日本 ; 歴史 ; 1945- ; KC521 ; 757.021",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784480068163",
    "jpno": null,
    "link": null,
    "title": "駅をデザインする",
    "titleKana": "エキ オ デザイン スル",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "ちくま新書",
    "seriesTitleKana": "チクマ シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "赤瀬 達三",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "筑摩書房",
    "publisherKana": null,
    "issued": null,
    "date": "2015-02-01",
    "price": 980,
    "extent": "254p",
    "pages": 254,
    "height": null,
    "subjects": "駅 ; KA294 ; 526.68",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784480067340",
    "jpno": null,
    "link": null,
    "title": "マーケットデザイン",
    "titleKana": "マーケット デザイン",
    "subtitle": "最先端の実用的な経済学",
    "subtitleKana": "サイセンタン ノ ジツヨウテキ ナ ケイザイガク",
    "seriesTitle": "ちくま新書",
    "seriesTitleKana": "チクマ シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "坂井 豊貴",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "筑摩書房",
    "publisherKana": null,
    "issued": null,
    "date": "2013-09-01",
    "price": 780,
    "extent": "232p",
    "pages": 232,
    "height": null,
    "subjects": "市場論 ; DA88 ; 331.845",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784480065728",
    "jpno": null,
    "link": null,
    "title": "35歳までに読むキャリアの教科書",
    "titleKana": "35サイ マデニ ヨム シゴト エラビ ノ キョウカショ",
    "subtitle": "就・転職の絶対原則を知る",
    "subtitleKana": "シュウ テンショク ノ ゼッタイ ゲンソク オ シル",
    "seriesTitle": "ちくま新書",
    "seriesTitleKana": "チクマ シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "渡邉 正裕",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "筑摩書房",
    "publisherKana": null,
    "issued": null,
    "date": "2010-10-01",
    "price": 820,
    "extent": "266p",
    "pages": 266,
    "height": null,
    "subjects": "キャリアデザイン ; EL121 ; 366.29",
    "subjectKana": "[]"
  },
  {
    "isbn": "4480059709",
    "jpno": null,
    "link": null,
    "title": "情報デザイン入門",
    "titleKana": "ジョウホウ デザイン ニュウモン",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "ちくま新書",
    "seriesTitleKana": "チクマ シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "木村 浩",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "筑摩書房",
    "publisherKana": null,
    "issued": null,
    "date": "2002-10-01",
    "price": 680,
    "extent": "174p",
    "pages": 174,
    "height": null,
    "subjects": "デザイン ; KC521 ; 727",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784062579285",
    "jpno": null,
    "link": null,
    "title": "直感を裏切るデザイン・パズル",
    "titleKana": "チョッカン オ ウラギル デザイン パズル",
    "subtitle": "脳と勝負する",
    "subtitleKana": "ノウ ト ショウブ スル",
    "seriesTitle": "ブルーバックス",
    "seriesTitleKana": "ブルー バックス",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "馬場 雄二",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "講談社",
    "publisherKana": null,
    "issued": null,
    "date": "2015-08-01",
    "price": 780,
    "extent": "190p",
    "pages": 190,
    "height": null,
    "subjects": "パズル ; Y78 ; 798",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784062578134",
    "jpno": null,
    "link": null,
    "title": "研究発表のためのスライドデザイン",
    "titleKana": "ケンキュウ ハッピョウ ノ タメ ノ スライド デザイン",
    "subtitle": "「わかりやすいスライド」作りのルール",
    "subtitleKana": "ワカリヤスイ スライドズクリ ノ ルール",
    "seriesTitle": "ブルーバックス",
    "seriesTitleKana": "ブルー バックス",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "宮野 公樹",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "講談社",
    "publisherKana": null,
    "issued": null,
    "date": "2013-04-01",
    "price": 900,
    "extent": "169p",
    "pages": 169,
    "height": null,
    "subjects": "プレゼンテーション ; DH314 ; 336.49",
    "subjectKana": "[]"
  },
  {
    "isbn": "4061181866",
    "jpno": null,
    "link": null,
    "title": "食生活をデザインする",
    "titleKana": "ショクセイカツ オ デザインスル",
    "subtitle": "栄養のタイミングとリズムが決め手",
    "subtitleKana": null,
    "seriesTitle": "ブルーバックス",
    "seriesTitleKana": null,
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "鈴木 正成",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "講談社",
    "publisherKana": null,
    "issued": null,
    "date": "1984-11-01",
    "price": 520,
    "extent": "193, 3p",
    "pages": 196,
    "height": null,
    "subjects": "食生活 ; SC87 ; 498.5",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784122051133",
    "jpno": null,
    "link": null,
    "title": "デザインの原像",
    "titleKana": "デザイン ノ ゲンゾウ",
    "subtitle": "かたちの詩学 2",
    "subtitleKana": "カタチ ノ シガク",
    "seriesTitle": "中公文庫",
    "seriesTitleKana": "チュウコウ ブンコ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "向井 周太郎",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "中央公論新社",
    "publisherKana": null,
    "issued": null,
    "date": "2009-01-01",
    "price": 1143,
    "extent": "261p",
    "pages": 261,
    "height": null,
    "subjects": "芸術 ; K21 ; 704",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784122061996",
    "jpno": null,
    "link": null,
    "title": "装飾とデザイン",
    "titleKana": "ソウショク ト デザイン",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "中公文庫",
    "seriesTitleKana": "チュウコウ ブンコ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "山崎 正和",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "中央公論新社",
    "publisherKana": null,
    "issued": null,
    "date": "2015-11-01",
    "price": 1000,
    "extent": "357p",
    "pages": 357,
    "height": null,
    "subjects": "装飾 ; 歴史 ; KC521 ; 757.02",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784122050532",
    "jpno": null,
    "link": null,
    "title": "生とデザイン",
    "titleKana": "セイ ト デザイン",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "中公文庫",
    "seriesTitleKana": "チュウコウ ブンコ. カタチ ノ シガク",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "向井 周太郎",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "中央公論新社",
    "publisherKana": null,
    "issued": null,
    "date": "2008-09-01",
    "price": 1143,
    "extent": "311p 図版15枚",
    "pages": 311,
    "height": null,
    "subjects": "芸術 ; K21 ; 704",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784121021847",
    "jpno": null,
    "link": null,
    "title": "コミュニティデザインの時代",
    "titleKana": "コミュニティ デザイン ノ ジダイ",
    "subtitle": "自分たちで「まち」をつくる",
    "subtitleKana": "ジブンタチ デ マチ オ ツクル",
    "seriesTitle": "中公新書",
    "seriesTitleKana": "チュウコウ シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "山崎 亮",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "中央公論新社",
    "publisherKana": null,
    "issued": null,
    "date": "2012-09-01",
    "price": 860,
    "extent": "255p",
    "pages": 255,
    "height": null,
    "subjects": "地域社会開発 ; 日本 ; EC63 ; 361.98",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784121020499",
    "jpno": null,
    "link": null,
    "title": "パリのグランド・デザイン",
    "titleKana": "パリ ノ グランド デザイン",
    "subtitle": "ルイ十四世が創った世界都市",
    "subtitleKana": "ルイ 14セイ ガ ツクッタ セカイ トシ",
    "seriesTitle": "中公新書",
    "seriesTitleKana": "チュウコウ シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "三宅 理一",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "中央公論新社",
    "publisherKana": null,
    "issued": null,
    "date": "2010-03-01",
    "price": 840,
    "extent": "276p",
    "pages": 276,
    "height": null,
    "subjects": "都市計画 ; フランス ; パリ ; 歴史 ; KA421 ; 518.8",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784121505484",
    "jpno": null,
    "link": null,
    "title": "だからデザイナーは炎上する",
    "titleKana": "ダカラ デザイナー ワ エンジョウ スル",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "中公新書ラクレ",
    "seriesTitleKana": "チュウコウ シンショ ラクレ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "藤本 貴之",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "中央公論新社",
    "publisherKana": null,
    "issued": null,
    "date": "2016-02-01",
    "price": 780,
    "extent": "206p",
    "pages": 206,
    "height": null,
    "subjects": "デザイン ; KC521 ; 757",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784121504616",
    "jpno": null,
    "link": null,
    "title": "ソーシャルデザイン50の方法",
    "titleKana": "ソーシャル デザイン ゴジュウ ノ ホウホウ",
    "subtitle": "あなたが世界を変えるとき",
    "subtitleKana": "アナタ ガ セカイ オ カエル トキ",
    "seriesTitle": "中公新書ラクレ",
    "seriesTitleKana": "チュウコウ シンショ ラクレ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "今 一生",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "中央公論新社",
    "publisherKana": null,
    "issued": null,
    "date": "2013-07-01",
    "price": 780,
    "extent": "245p",
    "pages": 245,
    "height": null,
    "subjects": "社会問題 ; EF1 ; 360",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784121503367",
    "jpno": null,
    "link": null,
    "title": "電車のデザイン",
    "titleKana": "デンシャ ノ デザイン",
    "subtitle": "カラー版",
    "subtitleKana": "カラーバン",
    "seriesTitle": "中公新書ラクレ",
    "seriesTitleKana": "チュウコウ シンショ ラクレ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "水戸岡 鋭治",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "中央公論新社",
    "publisherKana": null,
    "issued": null,
    "date": "2009-12-01",
    "price": 980,
    "extent": "205p",
    "pages": 205,
    "height": null,
    "subjects": "電車 ; NC37 ; 546.5",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784334043551",
    "jpno": null,
    "link": null,
    "title": "デザインが日本を変える",
    "titleKana": "デザイン ガ ニホン オ カエル",
    "subtitle": "日本人の美意識を取り戻す",
    "subtitleKana": "ニホンジン ノ ビイシキ オ トリモドス",
    "seriesTitle": "光文社新書",
    "seriesTitleKana": "コウブンシャ シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "前田 育男",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "光文社",
    "publisherKana": null,
    "issued": null,
    "date": "2018-05-01",
    "price": 800,
    "extent": "241p",
    "pages": 241,
    "height": null,
    "subjects": "自動車 ; 設計 ; NC23 ; 537.1",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784334103989",
    "jpno": null,
    "link": null,
    "title": "定年いたしません!",
    "titleKana": "テイネン イタシマセン",
    "subtitle": "「ジョブ型」時代の生き方・稼ぎ方",
    "subtitleKana": "ジョブガタ ジダイ ノ イキカタ カセギカタ",
    "seriesTitle": "光文社新書",
    "seriesTitleKana": "コウブンシャ シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "梅森 浩一",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "光文社",
    "publisherKana": null,
    "issued": null,
    "date": "2024-08-01",
    "price": 900,
    "extent": "264p",
    "pages": 264,
    "height": null,
    "subjects": "中高年齢者 ; キャリアデザイン ; 日本 ; EL125 ; 366.28",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784334103750",
    "jpno": null,
    "link": null,
    "title": "等身大の定年後",
    "titleKana": "トウシンダイ ノ テイネンゴ",
    "subtitle": "お金・働き方・生きがい",
    "subtitleKana": "オカネ ハタラキカタ イキガイ",
    "seriesTitle": "光文社新書",
    "seriesTitleKana": "コウブンシャ シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "奥田 祥子",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "光文社",
    "publisherKana": null,
    "issued": null,
    "date": "2024-07-01",
    "price": 880,
    "extent": "265p",
    "pages": 265,
    "height": null,
    "subjects": "中高年齢者 ; キャリアデザイン ; 日本 ; EL125 ; 366.28",
    "subjectKana": "[]"
  },
  {
    "isbn": "4334033660",
    "jpno": null,
    "link": null,
    "title": "100の悩みに100のデザイン",
    "titleKana": "100 ノ ナヤミ ニ 100 ノ デザイン",
    "subtitle": "自分を変える「解決法」",
    "subtitleKana": "ジブン オ カエル カイケツホウ",
    "seriesTitle": "光文社新書",
    "seriesTitleKana": "コウブンシャ シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "南雲 治嘉",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "光文社",
    "publisherKana": null,
    "issued": null,
    "date": "2006-08-01",
    "price": 780,
    "extent": "248p",
    "pages": 248,
    "height": null,
    "subjects": "人生訓 ; US51 ; 159",
    "subjectKana": "[]"
  },
  {
    "isbn": "4334032060",
    "jpno": null,
    "link": null,
    "title": "「情報を見せる」技術",
    "titleKana": "ジョウホウ オ ミセル ギジュツ",
    "subtitle": "ビジュアルセンスがすぐに身につく",
    "subtitleKana": "ビジュアル センス ガ スグニ ミニツク",
    "seriesTitle": "光文社新書",
    "seriesTitleKana": "コウブンシャ シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "中川 佳子",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "光文社",
    "publisherKana": null,
    "issued": null,
    "date": "2003-07-01",
    "price": 850,
    "extent": "253p 図版16枚",
    "pages": 253,
    "height": null,
    "subjects": "デザイン ; KC521 ; 727",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784098254408",
    "jpno": null,
    "link": null,
    "title": "デザイン思考2.0",
    "titleKana": "デザイン シコウ ニテンゼロ",
    "subtitle": "人生と仕事を変える「発想術」",
    "subtitleKana": "ジンセイ ト シゴト オ カエル ハッソウジュツ",
    "seriesTitle": "小学館新書",
    "seriesTitleKana": "ショウガクカン シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "松本 勝",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "小学館",
    "publisherKana": null,
    "issued": null,
    "date": "2023-02-01",
    "price": 900,
    "extent": "204p",
    "pages": 204,
    "height": null,
    "subjects": "思考 (経営管理) ; DH211 ; 336",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784005008261",
    "jpno": null,
    "link": null,
    "title": "生命デザイン学入門",
    "titleKana": "セイメイ デザインガク ニュウモン",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "岩波ジュニア新書",
    "seriesTitleKana": "イワナミ ジュニア シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "小川 葉子・太田 邦史",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "岩波書店",
    "publisherKana": null,
    "issued": null,
    "date": "2016-03-01",
    "price": 840,
    "extent": "210,4p",
    "pages": 214,
    "height": null,
    "subjects": "人間工学 ; Y11 ; 501.8",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784004313243",
    "jpno": null,
    "link": null,
    "title": "低炭素社会のデザイン",
    "titleKana": "テイタンソ シャカイ ノ デザイン",
    "subtitle": "ゼロ排出は可能か",
    "subtitleKana": "ゼロ ハイシュツ ワ カノウ カ",
    "seriesTitle": "岩波新書",
    "seriesTitleKana": "イワナミ シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "西岡 秀三",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "岩波書店",
    "publisherKana": null,
    "issued": null,
    "date": "2011-08-01",
    "price": 700,
    "extent": "187, 2p",
    "pages": 189,
    "height": null,
    "subjects": "二酸化炭素 ; 排出抑制 ; EG281 ; 519.3",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784004313335",
    "jpno": null,
    "link": null,
    "title": "日本のデザイン",
    "titleKana": "ニホン ノ デザイン",
    "subtitle": "美意識がつくる未来",
    "subtitleKana": "ビイシキ ガ ツクル ミライ",
    "seriesTitle": "岩波新書",
    "seriesTitleKana": "イワナミ シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "原 研哉",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "岩波書店",
    "publisherKana": null,
    "issued": null,
    "date": "2011-10-01",
    "price": 800,
    "extent": "244p",
    "pages": 244,
    "height": null,
    "subjects": "デザイン ; KC521 ; 757",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784582767278",
    "jpno": null,
    "link": null,
    "title": "柳宗理エッセイ",
    "titleKana": "ヤナギ ソウリ エッセイ",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "平凡社ライブラリー",
    "seriesTitleKana": "ヘイボンシャ ライブラリー",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "柳 宗理",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "平凡社",
    "publisherKana": null,
    "issued": null,
    "date": "2011-02-01",
    "price": 1300,
    "extent": "350p",
    "pages": 350,
    "height": null,
    "subjects": "工業デザイン ; M371 ; 501.83",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784582767094",
    "jpno": null,
    "link": null,
    "title": "ゼムクリップから技術の世界が見える",
    "titleKana": "ゼム クリップ カラ ギジュツ ノ セカイ ガ ミエル",
    "subtitle": "アイデアが形になるまで",
    "subtitleKana": "アイデア ガ カタチ ニ ナル マデ",
    "seriesTitle": "平凡社ライブラリー",
    "seriesTitleKana": "ヘイボンシャ ライブラリー",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "Petroski Henry・忠平 美幸",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "平凡社",
    "publisherKana": null,
    "issued": null,
    "date": "2010-09-01",
    "price": 1400,
    "extent": "338p",
    "pages": 338,
    "height": null,
    "subjects": "工業デザイン ; M371 ; 501.83",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784582766936",
    "jpno": null,
    "link": null,
    "title": "フォークの歯はなぜ四本になったか",
    "titleKana": "フォーク ノ ハ ワ ナゼ 4ホン ニ ナッタカ",
    "subtitle": "実用品の進化論",
    "subtitleKana": "ジツヨウヒン ノ シンカロン",
    "seriesTitle": "平凡社ライブラリー",
    "seriesTitleKana": "ヘイボンシャ ライブラリー",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "Petroski Henry・忠平 美幸",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "平凡社",
    "publisherKana": null,
    "issued": null,
    "date": "2010-01-01",
    "price": 1700,
    "extent": "467p",
    "pages": 467,
    "height": null,
    "subjects": "工業デザイン ; M371 ; 501.8",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784582856125",
    "jpno": null,
    "link": null,
    "title": "3・11後の建築と社会デザイン",
    "titleKana": "3 11 ゴ ノ ケンチク ト シャカイ デザイン",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "平凡社新書",
    "seriesTitleKana": "ヘイボンシャ シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "三浦 展・藤村 龍至",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "平凡社",
    "publisherKana": null,
    "issued": null,
    "date": "2011-11-01",
    "price": 760,
    "extent": "252p",
    "pages": 252,
    "height": null,
    "subjects": "居住福祉 ; 日本 ; EF52 ; 365.3",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784582855111",
    "jpno": null,
    "link": null,
    "title": "杉浦康平のデザイン",
    "titleKana": "スギウラ コウヘイ ノ デザイン",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "平凡社新書",
    "seriesTitleKana": "ヘイボンシャ シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "臼田 捷治",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "平凡社",
    "publisherKana": null,
    "issued": null,
    "date": "2010-02-01",
    "price": 860,
    "extent": "254p",
    "pages": 254,
    "height": null,
    "subjects": "杉浦, 康平, 1932- ; KC521 ; 727.021",
    "subjectKana": "[]"
  },
  {
    "isbn": "4582851150",
    "jpno": null,
    "link": null,
    "title": "形とデザインを考える60章",
    "titleKana": "カタチ ト デザイン オ カンガエル 60ショウ",
    "subtitle": "縄文の発想からCG技術まで",
    "subtitleKana": "ジョウモン ノ ハッソウ カラ CG ギジュツ マデ",
    "seriesTitle": "平凡社新書",
    "seriesTitleKana": "ヘイボンシャ シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "三井 秀樹",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "平凡社",
    "publisherKana": null,
    "issued": null,
    "date": "2001-11-01",
    "price": 780,
    "extent": "227p",
    "pages": 227,
    "height": null,
    "subjects": "形 (美術) ; K22 ; 701",
    "subjectKana": "[]"
  },
  {
    "isbn": "4582850960",
    "jpno": null,
    "link": null,
    "title": "情報デザイン入門",
    "titleKana": "ジョウホウ デザイン ニュウモン",
    "subtitle": "インターネット時代の表現術",
    "subtitleKana": "インターネット ジダイ ノ ヒョウゲンジュツ",
    "seriesTitle": "平凡社新書",
    "seriesTitleKana": "ヘイボンシャ シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "渡辺 保史",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "平凡社",
    "publisherKana": null,
    "issued": null,
    "date": "2001-07-01",
    "price": 720,
    "extent": "237p",
    "pages": 237,
    "height": null,
    "subjects": "情報処理 ; M151 ; 007.6",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784344986480",
    "jpno": null,
    "link": null,
    "title": "早期退職時代のサバイバル術",
    "titleKana": "ソウキ タイショク ジダイ ノ サバイバルジュツ",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "幻冬舎新書",
    "seriesTitleKana": "ゲントウシャ シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "小林 祐児",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "幻冬舎",
    "publisherKana": null,
    "issued": null,
    "date": "2022-03-01",
    "price": 980,
    "extent": "293p",
    "pages": 293,
    "height": null,
    "subjects": "中高年齢者 ; キャリアデザイン ; 日本 ; EL125 ; 366.28",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784344980198",
    "jpno": null,
    "link": null,
    "title": "あなたが年収1000万円稼げない理由。",
    "titleKana": "アナタ ガ ネンシュウ 1000マンエン カセゲナイ リユウ",
    "subtitle": "給料氷河期を勝ち残るキャリア・デザイン",
    "subtitleKana": "キュウリョウ ヒョウガキ オ カチノコル キャリア デザイン",
    "seriesTitle": "幻冬舎新書",
    "seriesTitleKana": "ゲントウシャ シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "田中 和彦",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "幻冬舎",
    "publisherKana": null,
    "issued": null,
    "date": "2007-01-01",
    "price": 720,
    "extent": "189p",
    "pages": 189,
    "height": null,
    "subjects": "キャリアデザイン ; EL121 ; 366.29",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784167904951",
    "jpno": null,
    "link": null,
    "title": "未来の働き方を考えよう",
    "titleKana": "ミライ ノ ハタラキカタ オ カンガエヨウ",
    "subtitle": "人生は二回、生きられる",
    "subtitleKana": "ジンセイ ワ ニカイ イキラレル",
    "seriesTitle": "文春文庫",
    "seriesTitleKana": "ブンシュン ブンコ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "ちきりん",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "文藝春秋",
    "publisherKana": null,
    "issued": null,
    "date": "2015-11-01",
    "price": 650,
    "extent": "238p",
    "pages": 238,
    "height": null,
    "subjects": "キャリアデザイン ; EL121 ; 366.29",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784167753399",
    "jpno": null,
    "link": null,
    "title": "ブランドのデザイン",
    "titleKana": "ブランド ノ デザイン",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "文春文庫",
    "seriesTitleKana": "ブンシュン ブンコ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "川島 蓉子",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "文藝春秋",
    "publisherKana": null,
    "issued": null,
    "date": "2009-02-01",
    "price": 714,
    "extent": "268p",
    "pages": 268,
    "height": null,
    "subjects": "商業美術 ; DH432 ; 674.3",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784101206561",
    "jpno": null,
    "link": null,
    "title": "電車をデザインする仕事",
    "titleKana": "デンシャ オ デザイン スル シゴト",
    "subtitle": "ななつ星、九州新幹線はこうして生まれた!",
    "subtitleKana": "ナナツボシ キュウシュウ シンカンセン ワ コウシテ ウマレタ",
    "seriesTitle": "新潮文庫",
    "seriesTitleKana": "シンチョウ ブンコ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "水戸岡 鋭治",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "新潮社",
    "publisherKana": null,
    "issued": null,
    "date": "2016-11-01",
    "price": 590,
    "extent": "238p",
    "pages": 238,
    "height": null,
    "subjects": "鉄道車両 ; NC34 ; 536",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784532262655",
    "jpno": null,
    "link": null,
    "title": "出世する人は人事評価を気にしない",
    "titleKana": "シュッセ スル ヒト ワ ジンジ ヒョウカ オ キ ニ シナイ",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "日経プレミアシリーズ",
    "seriesTitleKana": "ニッケイ プレミア シリーズ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "平康 慶浩",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "日本経済新聞出版社",
    "publisherKana": null,
    "issued": null,
    "date": "2014-10-01",
    "price": 850,
    "extent": "245p",
    "pages": 245,
    "height": null,
    "subjects": "キャリアデザイン ; DH311 ; 336.4",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784532262952",
    "jpno": null,
    "link": null,
    "title": "出世する人は一次会だけ参加します",
    "titleKana": "シュッセ スル ヒト ワ イチジカイ ダケ サンカ シマス",
    "subtitle": "会社人生を決める7つの選択",
    "subtitleKana": "カイシャ ジンセイ オ キメル ナナツ ノ センタク",
    "seriesTitle": "日経プレミアシリーズ",
    "seriesTitleKana": "ニッケイ プレミア シリーズ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "平康 慶浩",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "日本経済新聞出版社",
    "publisherKana": null,
    "issued": null,
    "date": "2015-11-01",
    "price": 850,
    "extent": "245p",
    "pages": 245,
    "height": null,
    "subjects": "キャリアデザイン ; DH311 ; 336.4",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784532263324",
    "jpno": null,
    "link": null,
    "title": "「中だるみ社員」の罠",
    "titleKana": "ナカダルミ シャイン ノ ワナ",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "日経プレミアシリーズ",
    "seriesTitleKana": "ニッケイ プレミア シリーズ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "山本 寛",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "日本経済新聞出版社",
    "publisherKana": null,
    "issued": null,
    "date": "2017-05-01",
    "price": 850,
    "extent": "197p",
    "pages": 197,
    "height": null,
    "subjects": "キャリアデザイン ; EL121 ; 366.29",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784532261825",
    "jpno": null,
    "link": null,
    "title": "「やりたい仕事」病",
    "titleKana": "ヤリタイ シゴトビョウ",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "日経プレミアシリーズ",
    "seriesTitleKana": "ニッケイ プレミア シリーズ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "榎本 博明",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "日本経済新聞出版社",
    "publisherKana": null,
    "issued": null,
    "date": "2012-11-01",
    "price": 850,
    "extent": "235p",
    "pages": 235,
    "height": null,
    "subjects": "キャリアデザイン ; EL121 ; 366.29",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784065316177",
    "jpno": null,
    "link": null,
    "title": "ロックをデザインする男サカグチケンdead start",
    "titleKana": "ロック オ デザイン スル オトコ サカグチ ケン デッド スタート",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "星海社新書",
    "seriesTitleKana": "セイカイシャ シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "サカグチ ケン",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "星海社",
    "publisherKana": null,
    "issued": null,
    "date": "2023-04-01",
    "price": 1600,
    "extent": "266p",
    "pages": 266,
    "height": null,
    "subjects": "サカグチ, ケン, 1964- ; KC521 ; 727.021",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784061385627",
    "jpno": null,
    "link": null,
    "title": "いいデザイナーは、見ためのよさから考えない",
    "titleKana": "イイ デザイナー ワ ミタメ ノ ヨサ カラ カンガエナイ",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "星海社新書",
    "seriesTitleKana": "セイカイシャ シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "有馬 トモユキ",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "星海社",
    "publisherKana": null,
    "issued": null,
    "date": "2015-04-01",
    "price": 840,
    "extent": "252p",
    "pages": 252,
    "height": null,
    "subjects": "デザイン ; KC521 ; 757",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784022952653",
    "jpno": null,
    "link": null,
    "title": "中高年リスキリング",
    "titleKana": "チュウコウネン リスキリング",
    "subtitle": "これからも必要とされる働き方を手にいれる",
    "subtitleKana": "コレカラ モ ヒツヨウ ト サレル ハタラキカタ オ テ ニ イレル",
    "seriesTitle": "朝日新書",
    "seriesTitleKana": "アサヒ シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "後藤 宗明",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "朝日新聞出版",
    "publisherKana": null,
    "issued": null,
    "date": "2024-08-01",
    "price": 900,
    "extent": "270p",
    "pages": 270,
    "height": null,
    "subjects": "中高年齢者 ; キャリアデザイン ; EL125 ; 366.28",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784309412672",
    "jpno": null,
    "link": null,
    "title": "デザインのめざめ",
    "titleKana": "デザイン ノ メザメ",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "河出文庫",
    "seriesTitleKana": "カワデ ブンコ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "原 研哉",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "河出書房新社",
    "publisherKana": null,
    "issued": null,
    "date": "2014-01-01",
    "price": 600,
    "extent": "147p",
    "pages": 147,
    "height": null,
    "subjects": "デザイン ; KC521 ; 757",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784309418940",
    "jpno": null,
    "link": null,
    "title": "独裁者のデザイン",
    "titleKana": "ドクサイシャ ノ デザイン",
    "subtitle": "ヒトラー、ムッソリーニ、スターリン、毛沢東の手法",
    "subtitleKana": "ヒトラー ムッソリーニ スターリン モウ タクトウ ノ シュホウ",
    "seriesTitle": "河出文庫",
    "seriesTitleKana": "カワデ ブンコ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "松田 行正",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "河出書房新社",
    "publisherKana": null,
    "issued": null,
    "date": "2022-06-01",
    "price": 1500,
    "extent": "395p",
    "pages": 395,
    "height": null,
    "subjects": "グラフィックアート ; 歴史 ; 20世紀 ; KC521 ; 727.02",
    "subjectKana": "[]"
  },
  {
    "isbn": "4560073392",
    "jpno": null,
    "link": null,
    "title": "デザインと行く",
    "titleKana": "デザイン ト ユク",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "白水Uブックス",
    "seriesTitleKana": "ハクスイ U ブックス. エッセイ ノ コミチ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "田中 一光",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "白水社",
    "publisherKana": null,
    "issued": null,
    "date": "1997-08-01",
    "price": 930,
    "extent": "214p",
    "pages": 214,
    "height": null,
    "subjects": "デザイン ; KC521 ; 727.04",
    "subjectKana": "[]"
  },
  {
    "isbn": "4560073708",
    "jpno": null,
    "link": null,
    "title": "われらデザインの時代",
    "titleKana": "ワレラ デザイン ノ ジダイ",
    "subtitle": "田中一光自伝",
    "subtitleKana": "タナカ イッコウ ジデン",
    "seriesTitle": "白水Uブックス",
    "seriesTitleKana": "ハクスイ U ブックス",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "田中 一光",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "白水社",
    "publisherKana": null,
    "issued": null,
    "date": "2004-04-01",
    "price": 950,
    "extent": "245, 3p",
    "pages": 248,
    "height": null,
    "subjects": "田中, 一光, 1930-2002 ; KC521 ; 727.021",
    "subjectKana": "[]"
  },
  {
    "isbn": "4062810395",
    "jpno": null,
    "link": null,
    "title": "ひらめき脳をつくるパズル「デザインQ」",
    "titleKana": "ヒラメキノウ オ ツクル パズル デザイン Q",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "講談社+α文庫",
    "seriesTitleKana": "コウダンシャ + アルファ ブンコ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "馬場 雄二",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "講談社",
    "publisherKana": null,
    "issued": null,
    "date": "2006-07-01",
    "price": 648,
    "extent": "234p",
    "pages": 234,
    "height": null,
    "subjects": "Y78 ; 798",
    "subjectKana": "[]"
  },
  {
    "isbn": "4062563738",
    "jpno": null,
    "link": null,
    "title": "家族の誰もが満足する「間取りと外観デザイン」900例",
    "titleKana": "カゾク ノ ダレ モガ マンゾクスル マドリ ト ガイカン デザイン 900レイ",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "講談社+α文庫",
    "seriesTitleKana": "コウダンシャ + アルファ ブンコ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "講談社",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "講談社",
    "publisherKana": null,
    "issued": null,
    "date": "1999-08-01",
    "price": 1200,
    "extent": "567p",
    "pages": 567,
    "height": null,
    "subjects": "住宅建築 ; NA241 ; 527.1",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784062881241",
    "jpno": null,
    "link": null,
    "title": "デザインの教科書",
    "titleKana": "デザイン ノ キョウカショ",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "講談社現代新書",
    "seriesTitleKana": "コウダンシャ ゲンダイ シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "柏木 博",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "講談社",
    "publisherKana": null,
    "issued": null,
    "date": "2011-09-01",
    "price": 720,
    "extent": "221p",
    "pages": 221,
    "height": null,
    "subjects": "デザイン ; KC521 ; 757",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784065181959",
    "jpno": null,
    "link": null,
    "title": "定年消滅時代をどう生きるか",
    "titleKana": "テイネン ショウメツ ジダイ オ ドウ イキルカ",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "講談社現代新書",
    "seriesTitleKana": "コウダンシャ ゲンダイ シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "中原 圭介",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "講談社",
    "publisherKana": null,
    "issued": null,
    "date": "2019-12-01",
    "price": 860,
    "extent": "230p",
    "pages": 230,
    "height": null,
    "subjects": "キャリアデザイン ; EL121 ; 366.29",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784062882354",
    "jpno": null,
    "link": null,
    "title": "20代のための「キャリア」と「仕事」入門",
    "titleKana": "ニジュウダイ ノ タメ ノ キャリア ト シゴト ニュウモン",
    "subtitle": null,
    "subtitleKana": null,
    "seriesTitle": "講談社現代新書",
    "seriesTitleKana": "コウダンシャ ゲンダイ シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "塩野 誠",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "講談社",
    "publisherKana": null,
    "issued": null,
    "date": "2013-11-01",
    "price": 740,
    "extent": "219p",
    "pages": 219,
    "height": null,
    "subjects": "キャリアデザイン ; EL121 ; 366.29",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784087210743",
    "jpno": null,
    "link": null,
    "title": "世界が変わる「視点」の見つけ方",
    "titleKana": "セカイ ガ カワル シテン ノ ミツケカタ",
    "subtitle": "未踏領域のデザイン戦略",
    "subtitleKana": "ミトウ リョウイキ ノ デザイン センリャク",
    "seriesTitle": "集英社新書",
    "seriesTitleKana": "シュウエイシャ シンショ",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "佐藤 可士和",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "集英社",
    "publisherKana": null,
    "issued": null,
    "date": "2019-04-01",
    "price": 780,
    "extent": "187p",
    "pages": 187,
    "height": null,
    "subjects": "デザイン ; KC521 ; 757",
    "subjectKana": "[]"
  },
  {
    "isbn": "9784413046589",
    "jpno": null,
    "link": null,
    "title": "人生の頂点(ピーク)は定年後",
    "titleKana": "ジンセイ ノ ピーク ワ テイネンゴ",
    "subtitle": "サードエイジ=「人生最良の時間」をどう迎えるか",
    "subtitleKana": "サード エイジ ジンセイ サイリョウ ノ ジカン オ ドウ ムカエルカ",
    "seriesTitle": "青春新書INTELLIGENCE",
    "seriesTitleKana": "セイシュン シンショ インテリジェンス",
    "seriesTitleVolume": null,
    "seriesTitleVolumeKana": null,
    "author": "池口 武志",
    "authors": "[]",
    "authorsKana": "[]",
    "publisher": "青春出版社",
    "publisherKana": null,
    "issued": null,
    "date": "2022-10-01",
    "price": 980,
    "extent": "188p",
    "pages": 188,
    "height": null,
    "subjects": "中高年齢者 ; キャリアデザイン ; EL125 ; 366.28",
    "subjectKana": "[]"
  }
]

export { stundentPicks, designBooks };
